local lunatest = require('tests.lunatest.lunatest')
local rps = require("RPS")

lunatest.suite('tests.test-cffi-interpret-function-pointer')
lunatest.suite('tests.test-cffi-interpret-struct')
lunatest.suite('tests.test-cffi-parser-function')
lunatest.suite('tests.test-cffi-parser-number')
lunatest.suite('tests.test-cffi-parser-string')
lunatest.suite('tests.test-cffi-parser-struct')
lunatest.suite('tests.test-code')
lunatest.suite('tests.test-detour-code')
lunatest.suite('tests.test-hook-code')
lunatest.suite('tests.test-issues')
lunatest.suite('tests.test-memory')
lunatest.suite('tests.test-string')
lunatest.suite('tests.test-success')
lunatest.run()
