
---@enum TOKEN_TYPES
local TOKEN_TYPES = {
  NONE = "NONE",
  DOUBLE_QUOTED_STRING = "DOUBLE_QUOTED_STRING",
  SINGLE_QUOTED_STRING = "SINGLE_QUOTED_STRING",
  LONG = "LONG",
  INTEGER = "INTEGER",
  HEXADECIMAL = "HEXADECIMAL",
  STRUCT = "STRUCT",
  SYMBOL = "SYMBOL",
  ENUM = "ENUM",
  UNION = "UNION",
  TYPEDEF = "TYPEDEF",
  CHARACTER = "CHARACTER",
  ARRAY_DIM = "ARRAY_DIM",
}

return {
  TOKEN_TYPES = TOKEN_TYPES,
}